command line interface improvements

diff --git a/scripts/strange-eval b/scripts/strange-eval
--- a/scripts/strange-eval
+++ b/scripts/strange-eval
@@ -15,8 +15,12 @@ for ARG in "$@"; do
 		TRIE="$(echo "$ARG" | awk -F'/' ' { printf $NF; }' | awk -F'.' ' { for( i = 1; i <= NF; ++i) if ($i != "") {print $i; break;} }').trie"
 		echo "Evaluating with $TRIE: $ARG"
 		strange $STRANGE_FLAGS -load="$STRANGE_HOME/$TRIE" -eval="$ARG"
+		EC=$?
+		if [ $EC -ne 0 ]; then
+			echo "ErrorCode $EC for $ARG" 1>&2
+		fi
 	else
-		echo "No such file: $ARG"
+		echo "No such file: $ARG" 1>&2
 	fi
 done
 
diff --git a/scripts/strange-learn b/scripts/strange-learn
--- a/scripts/strange-learn
+++ b/scripts/strange-learn
@@ -17,7 +17,12 @@ for ARG in "$@"; do
 		fi
 
 		strange $STRANGE_FLAGS "$LOAD_TRIE" -learn="$ARG" -save-compact="$STRANGE_HOME/$TRIE"
+		EC=$?
+		if [ $EC -ne 0 ]; then
+			echo "ErrorCode $EC for $ARG" 1>&2
+		fi
+
 	else
-		echo "No such file: $ARG"
+		echo "No such file: $ARG" 1>&2
 	fi
 done
